const state = {
    isNavigationOpen: false,
    chatMessages: [
        {
            message: "Hey! Are you coming to the party next door?",
            is_sender: false,
            time: "13:10",
        },
        {
            message: "Everyone's coming to the party!",
            is_sender: false,
            time: "13:11",
        },
        {
            message: "There will be tons of water to drink 😉",
            is_sender: false,
            time: "13:11",
        },
        {
            message: "Heeey! What time is the party starting?",
            is_sender: true,
            time: "13:12",
        },
        {
            message: "I guess I'll be there around 1800hrs in the evening",
            is_sender: true,
            time: "13:13",
        },
        {
            message: "The party will start @17:30hrs till late",
            is_sender: false,
            time: "13:15",
        },
        {
            message: "You better come early or you'll miss the free pizza!",
            is_sender: false,
            time: "13:16",
        },
        {
            message: "Tihihi! really free pizza?",
            is_sender: true,
            time: "13:17",
        },
        {
            message: "Yeah! There will be free pizza for early birds...",
            is_sender: false,
            time: "13:18",
        },
        {
            message: "You can keep some for meee! 😉",
            is_sender: true,
            time: "13:20",
        },
        {
            message: "Plus the free water",
            is_sender: true,
            time: "13:21",
        },
        {
            message: "We'll see about that!",
            is_sender: false,
            time: "13:22",
        },
        {
            message: "You only need to avail yourself early for the party..",
            is_sender: false,
            time: "13:23",
        },
        {
            message: "We'll see about that!",
            is_sender: true,
            time: "13:24",
        },
        {
            message: "You better be there early too",
            is_sender: true,
            time: "13:25",
        },
        {
            message: "He'll yeah, I'll be there early",
            is_sender: false,
            time: "13:26",
        },
    ],
    searchList: [
        {
            profile_image: "user1.jpeg",
            profile_name: "Jaykobpc",
            profile_lastseen: "Last seen yesterday at 23:40",
        },
        {
            profile_image: "user1.jpeg",
            profile_name: "Jaykobpc",
            profile_lastseen: "Last seen yesterday at 23:40",
        },
    ],
    chatListview: [
        {
            image: "user2.jpeg",
            name: "Cassie cage",
            message: "Party next door coming? 😉😉",
            time: "13:10",
            unread: true,
            counter: 2,
        },
        {
            image: "group1.jpeg",
            name: "Web Developers Group",
            message: "Koko: Everything is now working..",
            time: "13:05",
            unread: true,
            counter: 6,
        },
        {
            image: "user3.jpeg",
            name: "D'vora",
            message: "Dinner in the evening at my place...",
            time: "12:55",
            unread: true,
            counter: 2,
        },
        {
            image: "user4.jpeg",
            name: "Miss Christie",
            message: "Heey! My code is not running.. help!",
            time: "12:52",
            unread: true,
            counter: 4,
        },
        {
            image: "user5.jpeg",
            name: "Sarah webber",
            message: "Am just bored!",
            time: "12:50",
            unread: false,
            counter: 0,
        },
        {
            image: "group2.jpeg",
            name: "The Camping Group",
            message: "Andrea: Any one hanging out this weekend?",
            time: "12:45",
            unread: true,
            counter: 15,
        },
        {
            image: "group3.jpeg",
            name: "Drivers hub Group",
            message: "Liu kang: Motorcross this weekend tickets...",
            time: "12:40",
            unread: false,
            counter: 0,
        },
        {
            image: "user6.jpeg",
            name: "Jane Pearson",
            message: "Did you finish the art piece?",
            time: "12:30",
            unread: false,
            counter: 0,
        },
        {
            image: "user7.jpeg",
            name: "Andrew wiseman",
            message: "We sent the package today...",
            time: "12:10",
            unread: false,
            counter: 0,
        },
        {
            image: "user8.jpeg",
            name: "Fawaz Anwar",
            message: "We are working overtime on the project...",
            time: "11:50",
            unread: true,
            counter: 2,
        },
        {
            image: "user9.jpeg",
            name: "Jaykob wiseman",
            message: "Hahah... My code is now working",
            time: "12:00",
            unread: false,
            counter: 0,
        },
        {
            image: "user10.jpeg",
            name: "Monica Monaco",
            message: "Am moving to adelide next month...",
            time: "11:40",
            unread: true,
            counter: 2,
        },
        {
            image: "user11.jpeg",
            name: "Natasha Whitman",
            message: "This is really amazing, check 😉😉",
            time: "10:50",
            unread: false,
            counter: 0,
        },
        {
            image: "group4.jpeg",
            name: "The bubble Group",
            message: "Missouris: Thats what we want... 😉",
            time: "10:40",
            unread: true,
            counter: 5,
        },
    ],
}

export default state;